### ISSUE TITLE
Correction for Alternate function high register

### ISSUE THREAD

**Issue by doyleranpo** [atharvalele/stm32l476-cmsis-lib#1]
https://github.com/atharvalele/stm32l476-cmsis-lib/blob/3b39dd8bb20cee5e07e126b0af5c1a68ca965907/src/device/gpio.c#L122

For AFRH the value in the mask should be `I % 8`

Because the register is 32 bit. Passing `i` starting  from 8 and going up to 16 would cause the macro to expand to `4 * (8)`

Thus for the correct shift, it should be 
```c
portval &= ~GPIO_AF_SETT_MASK(i % 8);
portval |= GPIO_AF_SETT(i % 8, gpio_af);
```

**Comment by atharvalele** [comment]
Fixed!

Thanks for reporting.

https://github.com/atharvalele/stm32l476-cmsis-lib/commit/6bdbadd4fd830934a4fba5b41c38baeb49e154ff
